In [6]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
from sklearn import tree, metrics
from sklearn.metrics import accuracy_score
from sklearn.neighbors import DistanceMetric
# from sklearn.metrics import r2_score, f1_score
import sklearn
from sklearn.neighbors import NearestNeighbors
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import scale
from sklearn.model_selection import train_test_split


In [2]:
full_data = pd.read_csv("project_data_syntax_commands.csv", index_col = 0)

In [3]:
langs_list = list(full_data["Programming_Lang"].unique())
for i, lang in enumerate(langs_list):
    full_data = full_data.replace(lang,int(i))

In [4]:
data_set = full_data.copy()
data_set.drop(["User_Name","User_img","User_url","Sol_Code","Challange_Name","Variables Names"], axis = 1, inplace = True)

In [93]:
data_set[data_set["User_Gender"]==0]

Programming_Lang  User_Score  User's_Comments  User_Gender  Comments  \
0                    0          10                5            0         1   
2                    0           9                0            0         2   
4                    0           9                0            0         4   
12                   0           9                0            0         1   
14                   0          10                0            0         1   
...                ...         ...              ...          ...       ...   
2656                 0          10                0            0         3   
2657                 0          10                0            0         7   
2660                 0          10                0            0         7   
2664                 0          10                0            0         3   
2675                 0          10               -1            0        14   

      Conditions  For  While  do ... while  Func dec  Varibales Dec  Pointers  \
0             93   58      0           208        47              5         0   
2            124   56      0           206        58              1         0   
4             33  114     26           198        42              4         0   
12            83  103      0           208       118              5         0   
14           166   90      0           208        90              4         0   
...          ...  ...    ...           ...       ...            ...       ...   
2656           0    0      0             0         0              0         0   
2657           0    0      0             0         0              0         0   
2660           0    0      0             0         0              0         0   
2664           0    0      0             0         0              0         0   
2675           0    0      0             0         0              0         0   

      Comments length  code length  Num_of_Lines  Lines_ave_len  Vars_ave_len  \
0                  69          115            32             25             3   
2                 112          111            41             19             1   
4                 117          137            32             18             1   
12                330          178            45             23             7   
14                 94          147            36             25             3   
...               ...          ...           ...            ...           ...   
2656                0           26             2             16             0   
2657                0           29             5             15             0   
2660               24           25             6             22             0   
2664              134           28             2             16             0   
2675              100           34            12             15             0   

      num_of_cases_uses  Num_of_Vars  
0                     0           10  
2                     0            2  
4                     0            8  
12                    6           10  
14                    0           10  
...                 ...          ...  
2656                  0            0  
2657                  0            0  
2660                  0            0  
2664                  0            0  
2675                  0            0  

[798 rows x 19 columns]

In [86]:
male_df = data_set[data_set["User_Gender"]==0]
male_df = male_df.sample(n = 399, random_state = 2) 
drop_ind = male_df.index

In [100]:
equal_gender_data = data_set.drop(drop_ind,axis=0)

In [101]:
X = equal_gender_data.drop(["User_Gender"],axis=1).copy()
y = equal_gender_data.loc[:,"User_Gender"]

In [102]:
# X = scale(X)
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=0)

In [103]:
X_train.shape, X_test.shape

((558, 18), (240, 18))

In [148]:
clf1 = tree.DecisionTreeClassifier(max_depth=5,min_samples_split=3)
clf2 = RandomForestClassifier(n_estimators=90, max_depth=15,min_samples_split=15)
clf3 = KNeighborsClassifier(n_neighbors=20)

algs = ["DT","RandForest","KNN"]
clfs = [clf1,clf2,clf3]

for i,clf in enumerate(clfs):
    clf.fit(X_train,y_train)
    print(algs[i])
    print("======")
    y_pred = clf.predict(X_test)
    y_pred_train = clf.predict(X_train)
    
    print("accuracy on train data",metrics.accuracy_score(y_true=y_train,y_pred=y_pred_train))
    print("accuracy on test data",metrics.accuracy_score(y_true=y_test,y_pred=y_pred))
    
    print(metrics.confusion_matrix(y_test,y_pred))

DT
accuracy on train data 0.6451612903225806
accuracy on test data 0.5791666666666667
[[91 35]
 [66 48]]
RandForest
accuracy on train data 0.9408602150537635
accuracy on test data 0.5541666666666667
[[62 64]
 [43 71]]
KNN
accuracy on train data 0.5985663082437276
accuracy on test data 0.5416666666666666
[[70 56]
 [54 60]]
